### ISSUE TITLE
decimal poins

### ISSUE THREAD

**Issue by berkesandor** [anxzhu/segment-lcd-with-ht1621#6]
Hi! Can you give me an idea, how can I drive decimal poins individually?

**Comment by anxzhu** [comment]
A decimal point is choosed automated.
wrone(0, 0x80);
wrone(2, 0x80);
wrone(4, 0x80);

**Comment by berkesandor** [comment]
I wish to set the point manually, is there any command for this?

**Comment by Testato** [comment]
@berkesandor or @anxzhu 

by mistake berkesandor asked this same question in the Pull Request section.
Please close it
https://github.com/anxzhu/segment-lcd-with-ht1621/pull/5

**Comment by Testato** [comment]
@anxzhu,
I do not mean close this issue, but close the  Pull Request so the author of the fork, @5N44P can crrate his Pull Request
